---
ansible_user   : bender
ansible_password : n0passZX
ansible_sudo_pass : n0passZX
host_user      : testuser
host_password  : 12345678
data_archives : /opt/data_archives/
url_for_download : https://nginx.org/download/nginx-1.19.0.tar.gz
name_file_for_download : nginx-1.19.0.tar.gz