---
- name: Create a login user
  user:
    name: "{{ host_user }}"
    groups:
     - sudo
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: "/home/{{ host_user }}"